### ISSUE TITLE
test on own checkpoint

### ISSUE THREAD

**Issue by xuguozhi** [piddnad/AgileGAN#2]
hi, after we trained model on own dataset, how to test the checkpoints/best_model.pt?
I have replaced the low_path='pretrain/pixar.pt' to my own checkpoint, and get the corresponding error:
```Traceback (most recent call last):
  File "test.py", line 97, in <module>
    T=Tester(input_opts.model)
  File "test.py", line 26, in __init__
    g_ema.load_state_dict(checkpoint["g_ema"], strict=False)
KeyError: 'g_ema'```

**Comment by piddnad** [comment]
The test.py and files in the /lib/ folder come directly from [official inference code](https://github.com/flyingbread-elon/AgileGAN).
The /models/ folder is my own implementation, so it is slightly different from /libs/ in some detail. 
In summary, I think you can write a new test script like test.py to test your own model.

**Comment by xuguozhi** [comment]
seems like the
